---
name: CogML - CogServer Build
on:
  workflow_dispatch:
    inputs:
      cogutil_cache_key:
        description: 'Cache key for cogutil dependency'
        required: false
        type: string
      atomspace_cache_key:
        description: 'Cache key for atomspace dependency'
        required: false
        type: string
      cache_key_suffix:
        description: 'Cache key suffix for dependency builds'
        required: false
        default: 'default'
        type: string
  workflow_call:
    inputs:
      cogutil_cache_key:
        description: 'Cache key for cogutil dependency'
        required: false
        type: string
      atomspace_cache_key:
        description: 'Cache key for atomspace dependency'
        required: false
        type: string
      cache_key_suffix:
        description: 'Cache key suffix for dependency builds'
        required: false
        default: 'default'
        type: string

permissions:
  contents: read

jobs:
  cogserver:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    outputs:
      cache_key: ${{ steps.cache_info.outputs.key }}
    steps:
      - uses: actions/checkout@v4

      - name: Set cache info
        id: cache_info
        run: |
          echo "key=cogserver-${{ runner.os }}-${{ github.sha }}-${{ inputs.cache_key_suffix }}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libboost-all-dev guile-3.0-dev cython3 python3-nose valgrind doxygen

      - name: Install Cython
        run: python3 -m pip install --upgrade pip cython

      - name: Restore dependency caches
        uses: actions/cache@v3
        with:
          path: |
            orc-dv/cogutil/build
            orc-as/atomspace/build
          key: dependencies-${{ inputs.cogutil_cache_key }}-${{ inputs.atomspace_cache_key }}
          restore-keys: |
            cogutil-${{ runner.os }}-
            atomspace-${{ runner.os }}-

      - name: Build and install dependencies
        run: |
          # Build and install cogutil
          cd orc-dv/cogutil
          if [ ! -d "build" ]; then mkdir -p build; fi
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          sudo make install
          sudo ldconfig

          # Build and install atomspace
          cd ../../orc-as/atomspace
          if [ ! -d "lib" ]; then
            mkdir -p lib
            echo "# Empty lib directory for build compatibility" > lib/CMakeLists.txt
          fi
          if [ ! -d "build" ]; then mkdir -p build; fi
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Build CogServer
        run: |
          cd orc-sv/cogserver
          mkdir -p build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Test CogServer
        run: |
          cd orc-sv/cogserver/build
          make test || true

      - name: Install CogServer
        run: |
          cd orc-sv/cogserver/build
          sudo make install
          sudo ldconfig

      - name: Cache CogServer build
        uses: actions/cache@v3
        with:
          path: orc-sv/cogserver/build
          key: ${{ steps.cache_info.outputs.key }}

      - name: Create build artifacts summary
        run: |
          echo "## CogServer Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ✅ Success" >> $GITHUB_STEP_SUMMARY
          echo "- **Cache Key**: \`${{ steps.cache_info.outputs.key }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Path**: \`orc-sv/cogserver/build\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Dependencies**: cogutil, atomspace" >> $GITHUB_STEP_SUMMARY
          ls -la orc-sv/cogserver/build/ >> $GITHUB_STEP_SUMMARY || true