---
name: CogML - Moses Build
on:
  workflow_dispatch:
    inputs:
      cogutil_cache_key:
        description: 'Cache key for cogutil dependency'
        required: false
        type: string
      cache_key_suffix:
        description: 'Cache key suffix for dependency builds'
        required: false
        default: 'default'
        type: string
  workflow_call:
    inputs:
      cogutil_cache_key:
        description: 'Cache key for cogutil dependency'
        required: false
        type: string
      cache_key_suffix:
        description: 'Cache key suffix for dependency builds'
        required: false
        default: 'default'
        type: string

permissions:
  contents: read

jobs:
  moses:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    outputs:
      cache_key: ${{ steps.cache_info.outputs.key }}
    steps:
      - uses: actions/checkout@v4

      - name: Set cache info
        id: cache_info
        run: |
          echo "key=moses-${{ runner.os }}-${{ github.sha }}-${{ inputs.cache_key_suffix }}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          # Install packages in smaller chunks to prevent timeout
          sudo apt-get update -q
          sudo apt-get install -y -q build-essential cmake
          sudo apt-get install -y -q libboost-all-dev
          sudo apt-get install -y -q python3-nose valgrind doxygen

      - name: Build Moses
        run: |
          cd orc-ai/moses
          mkdir -p build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Test Moses
        run: |
          cd orc-ai/moses/build
          make test || true

      - name: Install Moses
        run: |
          cd orc-ai/moses/build
          sudo make install
          sudo ldconfig

      - name: Cache Moses build
        uses: actions/cache@v3
        with:
          path: orc-ai/moses/build
          key: ${{ steps.cache_info.outputs.key }}

      - name: Create build artifacts summary
        run: |
          echo "## Moses Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ✅ Success" >> $GITHUB_STEP_SUMMARY
          echo "- **Cache Key**: \`${{ steps.cache_info.outputs.key }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Path**: \`orc-ai/moses/build\`" >> $GITHUB_STEP_SUMMARY
          ls -la orc-ai/moses/build/ >> $GITHUB_STEP_SUMMARY || true