name: CogML 1 (cogutil)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:

  # ==== Foundation ====
  cogutil:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full git history for versioning
      
      - name: Update package lists
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update --fix-missing -y
        timeout-minutes: 5
        
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y --no-install-recommends build-essential cmake libboost-all-dev python3-nose valgrind doxygen
        timeout-minutes: 10
        retries: 3
          
      - name: Build cogutil
        run: |
          cd orc-dv/cogutil
          mkdir -p build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          
      - name: Test cogutil
        run: |
          cd orc-dv/cogutil/build
          make test || true
          
      - name: Install cogutil
        run: |
          cd orc-dv/cogutil/build
          sudo make install
          sudo ldconfig
          
      - name: Cache cogutil build
        uses: actions/cache@v3
        with:
          path: orc-dv/cogutil/build
          key: cogutil-${{ runner.os }}-${{ github.sha }}


